from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", views.mylogin,name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r'index_schueler/$', views.IndexS.as_view(), name="index_schueler"),
    url(r'index_lehrer/$', views.IndexL.as_view(), name="index_lehrer"),
    url(r'new/$', views.EngVocCreate.as_view(), name="new_eng"),
    url(r'test_going/$', views.test_view,name='mytest'),
    url(r'test_question/$', views.Testqu.as_view(),name='testqu'),
    url(r'new_schueler/$', views.signup, name='newschueler'),
    url(r'verwaltung/$', views.uebersicht, name='uebersicht'),
    url(r'kurs/(?P<pk>\d+)/$', views.KursDetailView.as_view(), name='kursdetail'),
    url(r'klassen/$', views.KlassenListView.as_view(), name='klassenuebersicht'),
    url(r'klassen/erstellen/$', views.KlasseCreateView.as_view(), name='newklasse'),
    url(r'klassen/loeschen/(?P<pk>\d+)/$', views.KlasseDelete.as_view(), name='klasse_del'),
    url(r'klassen/update/(?P<pk>\d+)/$', views.KlasseUpdate.as_view(), name='klasse_up'),
    url(r'nummer/(?P<pk>\d+)/$', views.KlassenDetailView.as_view(), name='schueleruebersicht'),
    url(r'verwaltung/kurs/(?P<pk>\d+)/schueler/$', views.plusschueler, name='schueler_plus'),
    url(r'verwaltung/kurs/(?P<pk>\d+)/schueler/(?P<myid>\d+)/$', views.plusschueler, name='schueler_plus'),
    url(r'verwaltung/kurs/(?P<pk>\d+)/schueler/entfernen/(?P<myid>\d+)/(?P<act>\d+)/$', views.plusschueler, name='schueler_plus'),
    url(r'schueler/(?P<pk>\d+)/$', views.SchuelerUpdateView.as_view(), name='schuelerchange'),
    url(r'thema/official/(?P<pk>\d+)/$', views.ThemaDetailOfficial.as_view(), name='thema_detail_official'),
    url(r'schueler/thema/(?P<pk>\d+)/$', views.ThemaDetailSchueler.as_view(), name='thema_detail_schueler'),
    url(r'thema/(?P<pk>\d+)/$', views.ThemaDetail.as_view(), name='thema_detail'),
    url(r'thema/liste/$', views.ThemaList.as_view(), name='themen'),
    url(r'thema/official/liste/$', views.ThemaListOfficial.as_view(), name='themen_official'),
    url(r'thema/schueler/liste/$', views.ThemaListSchueler.as_view(), name='themen_schueler'),
    url(r'profile/lehrer/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile, name='schuelerprofil'),
    url(r'profile/(?P<username>[a-zA-Z0-9]+)$', views.get_lehrer_profile, name='lehrerprofil'),
    url(r'profile/change_password/$', auth_views.password_change,{'template_name':'accounts/change_password.html', 'post_change_redirect':'accounts:password_change_done'}, name='changepwd'),
    url(r'profile/password_change_done/$', auth_views.password_change_done, {'template_name': 'accounts/password_change_done.html'},name='password_change_done'),
    url(r'password_reset/$', auth_views.password_reset,{'subject_template_name':'accounts/password_reset_subject.txt','email_template_name':'accounts/password_reset_email.html','post_reset_redirect':'accounts:password_reset_done'}, name='password_reset'),
    url(r'password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm,{'post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),
    url(r'reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'schueler/delete/(?P<pk>\d+)/$', views.SchuelerDelete.as_view(), name='schueler_del'),
    url(r'kurs/delete/(?P<pk>\d+)/$', views.KursDelete.as_view(), name='kurs_del'),
    url(r'kurs/erstellen/$', views.KursCreate.as_view(), name='newkurs'),
    url(r'kurs/update/(?P<pk>\d+)/$', views.KursUpdate.as_view(), name='kurs_up'),
    url(r'thema/erstellen/$', views.ThemaCreate.as_view(), name='newthema'),
    url(r'thema/delete/(?P<pk>\d+)/$', views.ThemaDelete.as_view(), name='thema_del'),
    url(r'thema/update/(?P<pk>\d+)/$', views.ThemaUpdate.as_view(), name='thema_up'),
    url(r'verwaltung/ohne/klasse/$', views.OhneKlasse.as_view(), name='ohne_klasse'),
    url(r'verwaltung/ohne/kurs/$', views.OhneKurs.as_view(), name='ohne_kurs'),
    url(r'add/all/klasse/(?P<pk>\d+)/$', views.all_klasse, name='add_all_klasse'),
    url(r'lehrer/stundenplan/add/$', views.LehrerPlanCreate.as_view(), name='lehrer_plan_add'),
    url(r'lehrer/stundenplan/zeile/add/$', views.lehrer_zeile_add, name='lehrer_zeile_add'),
    url(r'lehrer/stundenplan/zeile/(?P<pk>\d+)/edit/$', views.LehrerZeileUpdate.as_view(), name='lehrer_zeile_up'),
    url(r'lehrer/stundenplan/zeile/(?P<pk>\d+)/delete/$', views.LehrerZeileDelete.as_view(), name='lehrer_zeile_del'),
    url(r'lehrer/stundenplan/delete/(?P<pk>\d+)/$', views.LehrerPlanDelete.as_view(), name='lehrer_plan_del'),
    url(r'stundenplan/add/$', views.PlanCreate.as_view(), name='plan_add'),
    url(r'stundenplan/detail/(?P<pk>\d+)/$', views.PlanDetail.as_view(), name='plan_detail'),
    url(r'stundenplan/(?P<pk>\d+)/zeile/add/$', views.zeile_add, name='zeile_add'),
    url(r'stundenplan/zeile/(?P<pk>\d+)/edit/$', views.ZeileUpdate.as_view(), name='zeile_up'),
    url(r'stundenplan/zeile/(?P<pk>\d+)/delete/$', views.ZeileDelete.as_view(), name='zeile_del'),
    url(r'stundenplan/delete/(?P<pk>\d+)/$', views.PlanDelete.as_view(), name='plan_del'),
    url(r'schueler/profil/(?P<pk>\d+)/$', views.get_user_details, name='schueler_profil'),
    url(r'raum/add/$', views.RaumCreate.as_view(), name='raum_add'),
    url(r'raum/(?P<pk>\d+)/delete/$', views.RaumDelete.as_view(), name='raum_del'),
    url(r'raeume/liste/$', views.raum_liste, name='raum_list'),
    url(r'raum/(?P<pk>\d+)/update/$', views.RaumUpdate.as_view(), name='raum_up'),
    url(r'raum/(?P<pk>\d+)/detail/$', views.RaumDetail.as_view(), name='raum_detail'),
    url(r'lehrer/pk/stundenplan/detail/$', views.lehrer_plan_detail_pk, name='lehrer_plan_detail'),

]
