# Generated by Django 2.0.3 on 2018-03-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engvoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=200)),
                ('ndatum', models.DateField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Englisch-Vokabeln',
            },
        ),
        migrations.CreateModel(
            name='Ger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Engvoc')),
            ],
        ),
        migrations.CreateModel(
            name='Klassen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Klassen',
            },
        ),
    ]
