# Generated by Django 2.0.3 on 2018-03-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_klassen_lehrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klassen',
            name='lehrer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Lehrer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
