# Generated by Django 2.0.3 on 2018-03-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20180308_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Klassen')),
                ('lehrer', models.ForeignKey(limit_choices_to={'groups__name': 'Lehrer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fächer',
            },
        ),
    ]
