# Generated by Django 2.0.3 on 2018-03-13 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_fach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.RemoveField(
            model_name='fach',
            name='klasse',
        ),
        migrations.RemoveField(
            model_name='fach',
            name='lehrer',
        ),
        migrations.AddField(
            model_name='kurs',
            name='fach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Fach'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='klasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Klassen'),
        ),
        migrations.AddField(
            model_name='kurs',
            name='lehrer',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Lehrer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
