# Generated by Django 2.0.3 on 2018-03-14 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20180313_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='fach',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='klasse',
        ),
        migrations.AddField(
            model_name='kurs',
            name='teilnehmer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Teilnehmer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
