# Generated by Django 2.0.3 on 2018-03-14 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20180314_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='teilnehmer',
        ),
        migrations.AddField(
            model_name='kurs',
            name='teilnehmer',
            field=models.ManyToManyField(related_name='Teilnehmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
