# Generated by Django 2.0.3 on 2018-03-18 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180317_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='teilnehmer',
            field=models.ManyToManyField(blank=True, related_name='Teilnehmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
