# Generated by Django 2.0.3 on 2018-03-18 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20180318_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='stellvertreter',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lehrer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stellvertreter', to=settings.AUTH_USER_MODEL),
        ),
    ]
