# Generated by Django 2.0.3 on 2018-03-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_kurs_klasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raum', models.IntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Kurs')),
            ],
        ),
        migrations.CreateModel(
            name='Stundenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stundenplan', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Stundenpläne',
            },
        ),
        migrations.CreateModel(
            name='Zeile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.CharField(max_length=5)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stundenplan')),
            ],
        ),
        migrations.AddField(
            model_name='feld',
            name='z',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z', to='accounts.Zeile'),
        ),
    ]
