# Generated by Django 2.0.3 on 2018-03-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180322_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engvoc',
            options={'verbose_name': 'Englisch-Vokabel', 'verbose_name_plural': 'Englisch-Vokabeln'},
        ),
        migrations.AlterModelOptions(
            name='fach',
            options={'verbose_name': 'Fach', 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AlterModelOptions(
            name='feld',
            options={'verbose_name_plural': 'Felder'},
        ),
        migrations.AlterModelOptions(
            name='klassen',
            options={'verbose_name': 'Klasse', 'verbose_name_plural': 'Klassen'},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurse'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={'verbose_name': 'Thema', 'verbose_name_plural': 'Neuigkeiten'},
        ),
        migrations.AlterModelOptions(
            name='zeile',
            options={'verbose_name_plural': 'Zeilen'},
        ),
        migrations.AddField(
            model_name='stundenplan',
            name='klasse',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='accounts.Klassen'),
            preserve_default=False,
        ),
    ]
