# Generated by Django 2.0.3 on 2018-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180410_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeile',
            name='zeit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
