# Generated by Django 2.0.3 on 2018-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180411_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zeile',
            old_name='zeit',
            new_name='beginn',
        ),
        migrations.AddField(
            model_name='zeile',
            name='ende',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
