# Generated by Django 2.0.3 on 2018-04-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20180411_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='LehrerStundenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stundenplan', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Stundenpläne',
            },
        ),
        migrations.CreateModel(
            name='LehrerZeile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.TimeField(blank=True, null=True)),
                ('ende', models.TimeField(blank=True, null=True)),
                ('di', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ldi', to='accounts.Kurs')),
                ('do', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ldo', to='accounts.Kurs')),
                ('fr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lfr', to='accounts.Kurs')),
                ('mi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmi', to='accounts.Kurs')),
                ('mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmo', to='accounts.Kurs')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.LehrerStundenplan')),
            ],
            options={
                'verbose_name_plural': 'Zeilen',
            },
        ),
    ]
