# Generated by Django 2.0.3 on 2018-04-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_lehrerstundenplan_lehrerzeile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LehrerFeld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raum', models.IntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Kurs')),
                ('z', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z', to='accounts.LehrerZeile')),
            ],
            options={
                'verbose_name_plural': 'Felder',
            },
        ),
    ]
