# Generated by Django 2.0.3 on 2018-04-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180413_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.AlterModelOptions(
            name='lehrerfeld',
            options={'verbose_name_plural': 'Lehrer-Felder'},
        ),
        migrations.AlterModelOptions(
            name='lehrerzeile',
            options={'verbose_name_plural': 'Lehrer-Zeilen'},
        ),
        migrations.AlterField(
            model_name='feld',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs', to='accounts.Kurs'),
        ),
        migrations.AlterField(
            model_name='feld',
            name='raum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raum', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='lehrerfeld',
            name='z',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lz', to='accounts.LehrerZeile'),
        ),
        migrations.AddField(
            model_name='zeile',
            name='diraum',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='diraum', to='accounts.Raum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeile',
            name='doraum',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='doraum', to='accounts.Raum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeile',
            name='frraum',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='frraum', to='accounts.Raum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeile',
            name='miraum',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='miraum', to='accounts.Raum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zeile',
            name='moraum',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='moraum', to='accounts.Raum'),
            preserve_default=False,
        ),
    ]
