# Generated by Django 2.0.3 on 2018-04-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20180413_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeile',
            name='diraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raum_Dienstag', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='doraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raum_Donnerstag', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='frraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raum_Freitag', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='miraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raum_Mittwoch', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='moraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raum_Montag', to='accounts.Raum'),
        ),
    ]
