# Generated by Django 2.0.3 on 2018-04-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20180413_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeile',
            name='diraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diraum', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='doraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doraum', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='frraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frraum', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='miraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miraum', to='accounts.Raum'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='moraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moraum', to='accounts.Raum'),
        ),
    ]
