# Generated by Django 2.0.3 on 2018-04-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20180413_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belegung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('mo', 'Montag'), ('di', 'Dienstag'), ('mi', 'Mittwoch'), ('do', 'Donnerstag'), ('fr', 'Freitag')], max_length=2)),
                ('zeit', models.TimeField()),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Raum')),
            ],
            options={
                'verbose_name_plural': 'Belegungen',
            },
        ),
    ]
