# Generated by Django 2.0.3 on 2018-04-13 14:57

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_belegung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belegung',
            old_name='zeit',
            new_name='beginn',
        ),
        migrations.AddField(
            model_name='belegung',
            name='ende',
            field=models.TimeField(default=datetime.now().time()),
            preserve_default=False,
        ),
    ]
