# Generated by Django 2.0.3 on 2018-04-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180414_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehrerzeile',
            name='diraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ldiraum', to='accounts.Raum'),
        ),
        migrations.AddField(
            model_name='lehrerzeile',
            name='doraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ldoraum', to='accounts.Raum'),
        ),
        migrations.AddField(
            model_name='lehrerzeile',
            name='frraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lfrraum', to='accounts.Raum'),
        ),
        migrations.AddField(
            model_name='lehrerzeile',
            name='miraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmiraum', to='accounts.Raum'),
        ),
        migrations.AddField(
            model_name='lehrerzeile',
            name='moraum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmoraum', to='accounts.Raum'),
        ),
    ]
