# Generated by Django 2.0.3 on 2018-04-18 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0035_auto_20180417_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeile',
            name='dilehrer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lehrer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zeile',
            name='dolehrer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lehrer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dol', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zeile',
            name='frlehrer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lehrer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zeile',
            name='milehrer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lehrer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zeile',
            name='molehrer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lehrer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mol', to=settings.AUTH_USER_MODEL),
        ),
    ]
