# Generated by Django 2.0.3 on 2018-04-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20180418_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='belegung',
            name='course',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='accounts.Kurs'),
            preserve_default=False,
        ),
    ]
