# Generated by Django 2.0.4 on 2018-04-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_belegung_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeile',
            name='di',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='di', to='accounts.Kurs'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='do',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='do', to='accounts.Kurs'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='fr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr', to='accounts.Kurs'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='mi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi', to='accounts.Kurs'),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='mo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mo', to='accounts.Kurs'),
        ),
    ]
