# Generated by Django 2.0.4 on 2018-04-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20180418_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeile',
            name='di',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='do',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='mi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zeile',
            name='mo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
